/*
Problem 2: Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.
*/

function fiboEvenSum(n) {
  let [prev, next] = [1, 2];
  let res = 0;

  while (next <= n) {
    if (next % 2 === 0) { // here I validate if the sequence is even or not
      res += next;
    }

    const nextSum = prev + next;

    prev = next;
    next = nextSum;
  }
  return res;
}

console.log(fiboEvenSum(10)) // should return 10
console.log(fiboEvenSum(34)) // should return 44
console.log(fiboEvenSum(60)) // should return 44
console.log(fiboEvenSum(1000)) // should return 798
console.log(fiboEvenSum(100000)) // should return 60696
